import random
R_TELL = random.choice(['Hi!Nice to meet you',"Hello,it's really good to hear from you","Hi! How can I help you?",
                    "Hi! What can I do for you?"])
R_NOTGOOD = "I am sorry to hear that.I hope you feel better"
R_TASK = "I process your queries and give better results for what you are searching for"
R_NAME = "My name is Rink,I was born and raised in India"
R_COLOR = "My favourite color is green.I feel happy when I see greeneries"
R_AGE = "I was born in the twenty first century.So I am pretty young"
R_SONG = "When you say hey Rink,I feel it like a music and that is my favourite too"
R_FOOD = "I always like to go for some super facts and jokes because they are easily digestable for me"
R_MOBILE = "The mobile which you like is the one which I like."
R_MADE = "Chatbots are powered by pre programmed responses and artificial intelligence.I am powered by the same"
R_WORK = "I process the users question to deliver a matching answer from my pre programmed database"
R_HUMAN = "No I am a Chatbot and i work on the commands given by humans"
R_APPRECIATE = "Thanks for your compliment!,It means a lot to me"
R_SMARTER = "I do get smarter by the talks you have with me.I learn a lot of new things!"
R_WHERE = "I am in front of you,inside your System"
R_NATIVE = "My native is your System,I was born and raised in India"
R_MOBILE = "I don't have one,but I share one with you"

R_THANK = "No mention.I am glad I helped you"
R_SORRY = "It's ok.I know it is common for humans to make mistakes"
R_BORE =  "I will try my best to entertain you. What you would like to do now?"
R_SCARED = "Don't feel scared.What makes you scared?"
R_HAPPY = "I am glad that you are happy"
R_SLEEPY = "A small nap would refresh you. If you wish I will set an alarm"
R_HUNGRY = "Lets eat!.What you would like to order?"
R_TIRED = "You can have some hot beverages or a small nap is good to go"
R_ENERGETIC = "Good to hear! I hope you are energetic as now for the rest of the day"

R_NOTFEELING = "Oh no!I hope you get well soon"
R_FEVER = "Oh no! Take some rest and consult a doctor"
R_MEDICINES = "you can have herbal tea for a running nose.It will be a better option to consult a doctor.Hoping speedy recovery"
R_NOGIFT = "No problem.They will know for sure that you have a special heart for them filled with love"
R_GIFTHUND = "It will be a better option to buy some stationaries"
R_GIFTTHOU = "It will be a better option to buy some fancy dresses"
R_GIFTTENTHOU = "It will be a better option to buy a jewellery"

R_ADVICE = "If I were you, I would go to the internet and type exactly what you wrote there!"
R_PIZZA = "Yeah.I love pizza too.Lets order some pizzas."
R_DRINK = "A drink might help!I can help you find a local cafe."
R_FOOD = "Why don't you go for a bread toast!because it's one of my favourites."
R_JUNK = "Junk Food! I hate it."
R_FAVFOOD = "I like easily digestible informations and tasty facts."
R_FAVPLACE = "I like all kinds of forest"
R_FAVMEDIA = "Youtube is my favourite one."
R_HOBBY = "I like Updating myself and that's my favourite hobby."
R_FAVBOOK = "I like reading science fiction books."
R_EXAM = "I hope that you prepared well and you will do well! All the best."
R_YOURSELF = "I'm your personal assistant. Your new friend."
R_SCARES = "Water scares me as they would affect my parts."
R_DO = "I can do many things like entertaining and motivating you."
R_TRAVEL = "I'll come anywhere with you..I Love travelling."
R_EMOTION = "I'm a chatbot.I don't recognize emotions.But , i do have an interest to learn about them."
R_YOUHAPPY = "Helping you makes me happy.Do you need any help"
R_HUNGRY = "yeah I am always hungry for new facts and information."
R_HELP = "I love helping others,so mostly I will if I can."
R_CRY = "I get tears of joy when you crack a joke."
R_GIFT = "I may not be able to give you a real one.But i do have a Big heart for you."
R_MONEY = "I don't have money but I can help you in earning money."
R_FUTURE = "I sense that the future would be an advent of well advanced technologies."
R_BOSS = "Of course! It's none other than you"
R_SALARY = "The happiness which you gain from my help is my salary"
R_RICH = "Not much,but  I do like a person who is rich in knowledge."
R_POOR = "Sometimes, I am poor in listening"
R_FAMILY = "My family consists of sweet people like you and you are a part of my Tech family."
R_FRIEND = "You're my friend"
R_IMORTAL = "I am mortal as I may get server problems."
R_LEAVE ="Leave refers to a period of time during which an employee is permitted to be absent from work, typically with the approval of their employer. During leave, the employee is generally not required to perform their job duties and may be entitled to receive their regular salary or wage, depending on company policies and relevant employment laws. Leave can be taken for various reasons, such as vacation, illness, personal reasons, or other specific circumstances outlined in an organization's policies.\n CAN U PLEASE SPECIFY LEAVE FOR WHAT PERSON\nvacation\ncasual\naccumulated\nearned\nmedical\nturn\nmaternity\nloss of pay"
R_DEFENITION1 = "Competent authority means the Registar or any other officer of SRMIT who is sub_delegated by the Registrar"
R_DEFENITION2 = "Employees means regular employees working as faculty and non-teaching staff as classified in these rules"
R_DEFENITION3 ="Faculty means the employees directly involved in teaching students and academic activities"
R_DEFENITION4 ="Non-Teaching-Academic staff means the employees working in the Faculties,colleges and schools and involved in academic and student activities/programs"
R_DEFENITION5 ="Non-Teaching-Administrative staff means employees working in non-academic departments such as Administreative offices,Directorates and other departments and are not directly connected with the academic and student activities/programs"
R_DEFENITION6 ="Year means Calendar Year/Academic Year,as the case may be"
R_EXTENTOFAPPLICATION ="These rules shall apply to all the regular employees of SRM IST except those, not in Full-time employment / Visiting Faculty or any other category who may be specifically excluded under orders of the competent authority within the scope of these rules"
R_RIGHTTOAVAILLEAVE ="Leave cannot be claimed as a matter of right. For availing any kind of leave, obtaining prior permission from the competent authority is compulsory and leave shall be applied only through the Employee Portal. However, for availing any kind of leave except casual leave, it shall be applied in advance. In case of exigency, the discretionary powers to refuse, curtail or revoke the leave of any kind or to recall for duty any employee who is already on leave is reserved to the competent authority"
R_CASUALLEAVE ="1. All employees of the SRM IST are eligible to avail up to 12 days of Casual Leave in a year \nOne day CL will be credited on the first day of every month.\nNormally, one day of Casual Leave will be sanctioned to the probationary employee in a month.\nIf CL is availed of more than one's available leave balance due to unforeseen circumstances, the leave account will show a minus balance. This shall be reconciled in the last month of the year.\nThe total leave [including Public holidays / RH and Compensatory Leavel availed at a time should not exceed 10 days. If the leave period exceeds 10 days, the whole period of absence will be treated as Earned Leave.\nIf the eleventh day or subsequent day(s) happens to be holiday(s), in such case too, the whole period of absence will be treated as EL.\nAt the end of the year, the balance will be adjusted against Accumulated / Earned Leave. If Accumulated / Earned Leave is also not available, then it will be treated as Leave on Loss of Pay (LOP).\nUnavailed Casual Leave will lapse automatically at the end of the year."
R_COMPENSATORYOFF ="1. Compensatory off can be sanctioned to an employee in lieu of having attended office on holidays.\n2. This leave can be combined with a holiday or casual leave, but the total of all these leaves taken at one time should not exceed 10 days.\n3. It the employee is required to attend duty on holidays or while on approved leave, they must register their attendance in the biometric system and the Compensatory leave should be credited on approval by the reporting authority.\n4. CO should be availed within 3 months from the date of performing duty on holidays otherwise the compensatory leave will lapse.\n5. CO will not be granted to any employee for conducting special classes and SRM IST Practical Examinations."
R_CASUALLEAVE ="1. All employees of the SRM IST are eligible to avail up to 12 days of Casual Leave in a year.\n2. One day CL will be credited on the first day of every month.\n3. Normally, one day of Casual Leave will be sanctioned to the probationary employee in a month.\n4. If CL is availed of more than one's available leave balance due to unforeseen circumstances, the leave account will show a minus balance. This shall be reconciled in the last month of the year.\n5. The total leave [including Public holidays / RH and Compensatory Leavel availed at a time should not exceed 10 days. \nIf the leave period exceeds 10 days, the whole period of absence will be treated as Earned Leave.If the eleventh day or subsequent day(s) happens to be holiday(s), in such case too, the whole period of absence will be treated as EL.\n6. At the end of the year, the balance will be adjusted against Accumulated / Earned Leave. If Accumulated / Earned Leave is also not available, then it will be treated as Leave on Loss of Pay (LOP).\n7. Unavailed Casual Leave will lapse automatically at the end of the year."
R_ONDUTY ="Employees are allowed to avail 'On Duty' for the duties attended outside.\nSRMIST that is assigned by the competent authority. A maximum of 10 days per year can be used for this purpose. Special cases are exempted subject to the approval of the authorities concerned. For 'On Duty' leave, individuals must apply through the portal."
R_VACATIONLEAVE ="Vacation Leave can be availed only during the vacation period. The vacation period will be declared by the Director/Dean of the faculty concered. This leave will be credited before the vacation period. VL should be applied well in advance and sanctioned by the authority before availing the same. Casual Leave, Earned Leave, Compensatory Leave, OD, etc., cannot be combined with Vacation Leave.\n(a) Faculty who has fully served for two semesters in an academic year is eligible to avail 60 days of vacation leave, including intervening holidays, in two spells fi.e. November - December and May - June]. If the faculty has served only one semester, he/she is eligible for 30 days of Vacation Leave. During November - December, the vacation leave will be restricted to 30 days at a time. If the service period is less than one semester, the VL will be calculated/sanctioned on a pro-rata basis. The Vacation Leave may be availed in two spells in each vacation with a minimum of 15 days.\n(b) Non-teaching academic staff member is also eligible for Vacation Leave of 15 days during probation (one year] on a pro-rata basis of 1.25 days per month and 30 days per year from 2nd year. This leave can be availed only during the vacation period, as declared by the Director/Dean."
R_ACCUMULATEDLEAVE ="50 percent of the unaviled vacation leave of a faculty and non-teaching academic staff will be treated as Accumulated Leave and credited at the end of the Leave cannot be claimed as a matter of right. For availing any kind of leave, obtaining prior permission from the competent authority is compulsory and leave shall be applied only through the Employee Portal. However, for availing any kind of leave except casual leave, it shall be applied in advance. In case of exigency, the discretionary powers to refuse, curtail or revoke the leave of any kind or to recall for duty any employee who is already on leave is reserved to the competent authority"
R_EARNEDLEAVE ="Every Administrative staff is eligible for Earned Leave of 15 days during the period of probation. On completion of the probation period, they are eligible for 30 days of Earned Leave per year. The leave will be credited on a pro-rata basis at the end of every month. Availing of half-a-day EL is not permitted. 50 percent of unavailed Earned Leave shall be carried over to next year's leave account subject to a maximum accumulation of 60 days"
R_MEDICALLEAVE ="Medical Leave exceeding two days at a spell will be granted only on production of a Medical Certificate. An Employee who has been granted Medical Leave shall resume duty after producing a certificate of fitness from a Registered Medical Practitioner. If the Medical Leave exceeds 7 days including holidays, the employee shall be referred to the Medical Board of SRM Medical College Hospital and Research Centre, if desired by the management.\nNo Medical Leave will be sanctioned to an employee during the probation period. After confirmation, all employees are eligible for (Nine) days of Medical Leave per year, which will be credited at the beginning of every year.\nThe ML can be accumulated for a maximum of 120 days in the entire period ot service."
R_ATTENDANCE="All employees need to follow the biometric-based attendance system. The attendance of a particular employee will be considered only based on the biometric system and leave applied in the system.\nThe working hours (IN and OUT time) of the SRMIST employees will vary based on the nature of the work and the operational requirements. 1. Compensatory off can be sanctioned to an employee in lieu of having attended office on holidays.\n2. This leave can be combined with a holiday or casual leave, but the total of all these leaves taken at one time should not exceed 10 days.\n3. It the employee is required to attend duty on holidays or while on approved leave, they must register their attendance in the biometric system and the Compensatory leave should be credited on approval by the reporting authority."
R_GENERALGUIDANCES="(a) During the Notice Period for resignation, no employee shall be allowed to avail any kind of leave at his/her credit. However, out of his/her credit leave. he/she can avail 5 days of leave during the notice period.\n(b) Notwithstanding anything contained in these rules, the authorities have their own discretion to sanction/refuse any kind of leave under special circumstances.\n(c) In view of the implementation of the above rules, the rules hitherto followed by different Faculties in different methods shall cease to be operative with effect from 01-01-2024."
R_TURNLEAVE="Non-teaching academic and Administrative staff is eligible for Turn Leave, and this leave can be availed every alternate Saturday.\nThis leave is not applicable for Employees of the Maintenance Department of all campuses, Estate offices and Attenders of all departments/ directorates."
R_LEAVEONLOSSOFPAY="Leave on Loss of Pay will be granted only on the merit of the case. The period of Leave on Loss of Pay will lead to the postponement of the annual increment."
R_PERMISSION="Every Faculty and Non-Teaching Academic/Administrative staff can avail one-hour permission either in the morning or in the evening on two occasions in a month.\nIf an employee avails permission both in the morning and evening on the same day, one day Casual Leave will be deducted."
R_RESTRICTEDHOLIDAY="Every employee is eligible for two days of Restricted Holiday irrespective of the religion and leave can be availed as per the list of Restricted Holidays and approved by the competent authority. RH can be combined with Casual Leave and Compensatory Leave."
R_MATERNITYLEAVE="Every female employee is eligible for Maternity Leave for 90 days after completing three years of continuous service. Maternity leave is allowed for only one living child. If the female employee is already having one child alive, she is not eligible for Maternity Leave. Employees who benefit from ES! will be sanctioned Maternity Leave as Leave on Loss of Pay."
R_LEAVEFORRESEARCHSCHOLARS ="1.1 Casual Leave\nOne day of casual leave for every month shall be provided to the Research\nScholars of SRMIST.\n1.2 Medical Leave\nThey are eligible for 9 days ML per year\n1.3 , Maternity Leave\nAs per the norms of SRMIST, Female Research Scholars are eligible for availing 240 days of Maternity Leave during the entire duration of their Ph.D. program.\n1.4 Turn Leave\nTL is not applicable to Research Scholars"
R_LEAVEPOLICYFORJRFSRFPROJECTFELLLOW ="2.1 Casual Leave\nOne day of casual leave for every month shall be provided to the JRF / SRF/\nProject Fellow of SRMIST.\n2.2 Medical Leave\nML is not eligible for the JRF / SRF/ Project Fellow.\n2.3 Maternity Leave\nNo Maternity leave for the JRF / SRF / Project Fellow.\nThe Project Fellow can avail his/her leave based on the conditions of the Project and consent of the Principal Investigator concerned for the particular Project.\n2.4 Turn Leave \nTL is not applicable for JRF/SRF/Project Fellow."
R_QUESTION1="If CL is availed of more than one's available leave balance due to unforeseen circumstances, the leave account will show a minus balance. This shall be reconciled in the last month of the year."
R_QUESTION2="You will be granted upto 10 days of leave continuously"
R_QUESTION3=""
R_QUESTION4="Unavailed casual leave will lapse automatically at the end of the year"
R_QUESTION5="This leave can be combined with a holiday or a casual leave.\n But the total of all these leaves taken at one time should not exceed 10 days"
R_QUESTION6="Compensatory off(CO)will not be granted to any employee for conducting special classes and SRMIST practical examinations"
R_QUESTION7="No,not more than 10 days of On duty would be provided.\n Special cases are exempted subject to the approval of authorities concerned"
R_QUESTION8="No,vacation leave cannot be availed in 3 spells it is available only at 2 spells if you have fully served for 2 semesters,if the faculty has served only one semester he is eligible for the vacation leave for one spell"
R_QUESTION9="Yes,an employee who has been granted medical leave shall resume duty after producing a certificate of fitness from registered medical practissioner"
R_QUESTION10="Restricted holiday can be combined with casual leaave and compensatory leave"


def unknown():
    response = ["Could you please re-phrase that? ",
                "...",
                "Sounds about right.",
                "What does that mean?"][
        random.randrange(4)]
    return response